# Generated by Django 6.0.6 on 2026-06-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_customerservice_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanduanRakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=255)),
                ('deskripsi_singkat', models.TextField()),
                ('link_embed_youtube', models.URLField(help_text='Tulis URL embed YouTube, misal https://www.youtube.com/embed/xxxxxx')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Panduan Rakit',
                'verbose_name_plural': 'Panduan Rakit',
                'ordering': ['-created_at'],
            },
        ),
    ]
