# Generated by Django 6.0.6 on 2026-06-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_panduanrakit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Dibalas'),
        ),
        migrations.AddField(
            model_name='customerservice',
            name='reply_message',
            field=models.TextField(blank=True, null=True, verbose_name='Pesan Balasan Admin'),
        ),
    ]
