# Generated by Django 6.0.6 on 2026-06-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_customerservice_replied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor WhatsApp'),
        ),
    ]
