"""
Django settings for kucadi_project project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path
import dj_database_url # BARU: Ditambahkan untuk PostgreSQL Render

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file():
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


load_env_file()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# DIUBAH: Menggunakan Environment Variable di Render, kalau di lokal pakai default template kamu
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-u0bwcarc=7ncj=5@5*4so#&%i&7n7_nf4@49wdard2e+8xxe83')

# SECURITY WARNING: don't run with debug turned on in production!
# DIUBAH: Otomatis False kalau sudah di Render (Production), tetap True kalau di laptop kamu
DEBUG_VALUE = os.environ.get('DEBUG')
if DEBUG_VALUE is None:
    DEBUG = 'RENDER' not in os.environ
else:
    DEBUG = DEBUG_VALUE.lower() in {'1', 'true', 'yes', 'on'}

# DIUBAH: Menambahkan domain Render secara dinamis agar tidak error saat online
DEFAULT_ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'happy-caution-slaw.ngrok-free.dev,127.0.0.1,localhost,.vercel.app')
ALLOWED_HOSTS = [host.strip() for host in DEFAULT_ALLOWED_HOSTS.split(',') if host.strip()]

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

VERCEL_URL = os.environ.get('VERCEL_URL')
if VERCEL_URL:
    ALLOWED_HOSTS.append(VERCEL_URL)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'marketplace',
    
    # WAJIB DIBAWAH INI UNTUK SISTEM GOOGLE LOGIN
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # BARU: Wajib di sini untuk mengurus file CSS/JS di Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # BARU: Middleware wajib untuk django-allauth
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'kucadi_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Tambahkan path folder templates global di bawah ini
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'marketplace.context_processors.cart_item_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'kucadi_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DIUBAH: Otomatis pakai PostgreSQL kalau di Render, pakai SQLite kalau di laptop kamu
DATABASE_URL = os.environ.get('DATABASE_URL', f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
DATABASES = {
    'default': dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'id'
TIME_ZONE = 'Asia/Jakarta'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# BARU: Pengaturan penyimpanan Whitenoise agar kompresi aset berjalan optimal di server production
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads: product images, etc.)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'marketplace.User'


# =========================================================================
# BARU: KONFIGURASI TAMBAHAN UNTUK GOOGLE ALLAUTH
# =========================================================================
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = int(os.environ.get('SITE_ID', '1'))

# Arahkan redirect kembali ke halaman utama katalog setelah login/logout
LOGIN_REDIRECT_URL = os.environ.get('LOGIN_REDIRECT_URL', '/')
LOGOUT_REDIRECT_URL = os.environ.get('LOGOUT_REDIRECT_URL', '/')
LOGIN_URL = os.environ.get('LOGIN_URL', '/accounts/login/')

# Konfigurasi agar alur login Google berjalan mulus tanpa hambatan
ACCOUNT_LOGOUT_ON_GET = True
SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'

# =========================================================================
# EMAIL CONFIGURATION - DEVELOPMENT (Console Backend)
# =========================================================================
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')

# =========================================================================
# ALLAUTH EMAIL & SIGNUP CONFIGURATION
# =========================================================================
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_SIGNUP_REDIRECT_URL = '/'

# =========================================================================
# MIDTRANS PAYMENT GATEWAY CONFIGURATION
# =========================================================================
MIDTRANS_MERCHANT_ID = os.environ.get('MIDTRANS_MERCHANT_ID', 'M333639415')
MIDTRANS_CLIENT_KEY = os.environ.get('MIDTRANS_CLIENT_KEY', 'Mid-client-nvVOw_7nQXNbd7jU')
MIDTRANS_SERVER_KEY = os.environ.get('MIDTRANS_SERVER_KEY', '')
MIDTRANS_IS_PRODUCTION = os.environ.get('MIDTRANS_IS_PRODUCTION', 'False').lower() in {'1', 'true', 'yes', 'on'}


